### ISSUE TITLE
Ensuring that contributions will be made back into this repository.

### ISSUE THREAD

**Issue by MakisH** [waltsims/Thesis_Template_CSE#12]
Now that we got the thesis template on GitHub, I find is crucial to assume this repository as the "main" one and encourage everybody to contribute back to it to maintain it. A bad scenario that I can imagine is that people start sharing archives of the template or theses based on it, without the readme file.

I think it would be good to do the following, as soon as we fix any currently remaining issues:

- [ ] Add a link to this repository in the `main.tex` and in the `README.md` and ask for contributions and issues reporting.
- [ ] Add a contribution guide.
- [x] Ask the CSE coordinators to link to this repository instead of a snapshot of it. Archives could also be provided, but the user needs to be able to know where to find the latest version.

As part of this, we should also clarify that this is not an official template provided by TUM and maybe set a license for the files we can (notice that we don't own the TUM or the CSE logos, even though we are allowed to place them on the thesis).

What do you think?

**Comment by waltsims** [comment]
Last point has been done. See link [here](http://www.in.tum.de/fuer-studierende/master-studiengaenge/computational-science-and-engineering/thesis-information.html) on the upper right and the bottom of the page:
