### ISSUE TITLE
Hyperref: proper colouring for the links

### ISSUE THREAD

**Issue by MakisH** [waltsims/Thesis_Template_CSE#13]
When using the [hyperref](https://ctan.org/pkg/hyperref) package, the colors are useful in the pdf, but they shouldn't appear on the printed version.

I am currently working on this.

**Comment by waltsims** [comment]
Why shouldn't they? I have read published books where hyperreffed terms are highlighted.

**Comment by MakisH** [comment]
Because in the printed version they are not links, you cannot "click" on them, so they don't need to be discovered. Apart from this, they draw attention and they disturb the natural flow of the reading.

I guess that in those books the publisher just didn't take care of this. Most (maybe all) of the printed published books I have read typeset the links in the same color as the surrounded text.

**Comment by waltsims** [comment]
This looks promising:http://tex.stackexchange.com/questions/230752/can-i-have-hyperlinks-a-different-color-for-printing
