### ISSUE TITLE
Preface is not included anywhere.

### ISSUE THREAD

**Issue by MakisH** [waltsims/Thesis_Template_CSE#16]
The preface exists as a file, but is not included anywhere. We should either allow an option for this, or drop it. I vote to include it, as it can be useful.

We need to define if it is accepted as a part of the thesis though. In my oppinion this is an optional element of a book and the same holds for the quote.

**Comment by waltsims** [comment]
a book doesn't have an abstract, a thesis does.  What would one say in the preface that wouldn't be put in the acknowledgments, the introduction or the abstract?  The quote was my addition. If you feel we should make it to an option or get rid of it I am open to that.

**Comment by MakisH** [comment]
Actually "acknowledgements" is usually a part of preface. In the preface of a book, the author can also add more elements, like how he got the idea or why he wrote this book.

I think that indeed, in the context of the thesis it doesn't really make sense to have a separate section for this. We could either incorporate it in the "Acknowledgements" (e.g. **change the title to "Preface"**) or delete it.

**Do we have any good source/argumentation that could help us take a decision on this?**

Note: `preface.tex` is used neither in the previous version on the template nor in the Informatics template (which it is based on).

**Comment by waltsims** [comment]
http://www.writersandeditors.com/preface__foreword__or_introduction__57375.htm <http://www.writersandeditors.com/preface__foreword__or_introduction__57375.htm>

https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/advanced_avionics_handbook/media/aah_front.pdf <https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/advanced_avionics_handbook/media/aah_front.pdf>

One can either have them listed together or separately. I vote for separately so every author can choose for themselves what they would like to include and what they would like to omit.

I added preface.tex
