### ISSUE TITLE
Document and cleanup the commands.tex

### ISSUE THREAD

**Issue by MakisH** [waltsims/Thesis_Template_CSE#17]
Several promising custom commands are included in the `components/commands.tex`, but they don't have more than a short line of comment to describe them. Moreover, some of them may not work or they may not be implemented in a proper way.

We should check and document them. An example sheet would also be nice.

**Comment by waltsims** [comment]
@benjaminaaron maybe you would like to tackle this?

**Comment by benjaminaaron** [comment]
I'll keep on eye on this while writing my thesis 👍
