### ISSUE TITLE
Usage of \include{} vs \input{}

### ISSUE THREAD

**Issue by MakisH** [waltsims/Thesis_Template_CSE#21]
As discussed in [this question](https://tex.stackexchange.com/questions/246/when-should-i-use-input-vs-include), using `\include{}` instead of `\input{}` can significantly decrease the compilation time in big projects, when changing only one part of the document, as it creates a different `.aux` file for each file. However, there are places were only `\input{}` can be used.

Currently we are only using `\input{}` everywhere. We should investigate where we can implement this.

I will work on this soon.

**Comment by MakisH** [comment]
I read again the whole discussion and I am not sure if this would be a good change.

Long story short, it would mainly make sense if used together with the `\includeonly{}` statement, to specify which files (chapters) to include in the intermediate compilation phases.

There are also comments in which a performance decrease is stated when using the `\include{}` without also using the `\includeonly{}`.

In order to implement it, we simply have to change the `\input{}` statements to `\include{}` only in the `components/text.tex`. Other components cannot be used like this or it doesn't make sense to do so. Keep in mind that `include{}` also does a `\clearpage` before and after the included statements and cannot be nested.

I leave this open for now, I will test it in the future with a long, actual text. Of course, if anyone else wants to try it, you are welcome to do so! :-)

**Comment by waltsims** [comment]
Since it's unclear if this is needed I'm closing for now.
