### ISSUE TITLE
Longer Titles

### ISSUE THREAD

**Issue by irvcaza** [waltsims/Thesis_Template_CSE#24]
There is a problem When you try to insert longer titles, for example, change [this line](https://github.com/waltsims/Thesis_Template_CSE/blob/master/components/info.tex#L12) for 
`\def\title{My Ticket to a Masters Degree but a little longer}`
provokes the following
![longer](https://user-images.githubusercontent.com/15790161/28461072-47e954ea-6e15-11e7-8ed8-38a701881704.PNG)

**Comment by irvcaza** [comment]
This can be solved easily changing [this line](https://github.com/waltsims/Thesis_Template_CSE/blob/master/components/cover.tex#L31) for 
`	\vspace{\fill}`
Then the cover will appear again correctly
![longer_filled](https://user-images.githubusercontent.com/15790161/28461280-2ae77cb8-6e16-11e7-90bd-a5272d17ec9d.PNG)

**Comment by waltsims** [comment]
looks good! I'd be happy to accept your pull request.

**Comment by irvcaza** [comment]
Apparently, for even longer titles this also affects the [title page](https://github.com/waltsims/Thesis_Template_CSE/blob/master/components/titlepage.tex). Let me Investigate further if this problem exists in some other places.
Also if you have some ideas about other places with this delicate structure please let me know.

**Comment by waltsims** [comment]
fixed with https://github.com/waltsims/Thesis_Template_CSE/commit/e751cb1bdaa05a5dba0700dcac3ca847054855b6
