### ISSUE TITLE
company logo?

### ISSUE THREAD

**Issue by benjaminaaron** [waltsims/Thesis_Template_CSE#27]
Thanks so much for providing and maintaining this template, super useful :+1:

When one writes their thesis with a company - should their logo be added next to the TUM Logo? :thinking: 
If so, on both cover and titlepage? That might be nice to include as out-commented option in the template. I'd be happy to create a pull request that adds this.

**Comment by waltsims** [comment]
I'm not sure what the requirements of the TUM are in this regard. I would ask you to please ask your Thesis adviser to see whether that is in accordance with TUM policy.

**Comment by waltsims** [comment]
Any progress on this front? @benjaminaaron

**Comment by benjaminaaron** [comment]
I was told that it's not common to add the company logo, so I won't do it.
