### ISSUE TITLE
remove horizontal line above page number?

### ISSUE THREAD

**Issue by benjaminaaron** [waltsims/Thesis_Template_CSE#31]
An idea how I could remove the horizontal line above the page number on the bottom of most (why not all?) pages? Footnotes are placed above it. I can't seem to find where that is set or what packages does that. Googled quite a bit already :mag: 

Screenshot of what I mean:

![image](https://user-images.githubusercontent.com/5141792/54311721-7da7a480-45d5-11e9-885e-84adadfe2594.png)

**Comment by waltsims** [comment]
I think you just want to remove [this](https://github.com/waltsims/TUM_Thesis_Template_CSE/blob/59cf815a66746c13a48ab3f026b139cc7dfb9fc6/main.tex#L37) argument  the document constructor. Let me know if you have any luck.

**Comment by benjaminaaron** [comment]
Ahh, yes! Thanks, that's it :+1:
