### ISSUE TITLE
red rectangles in minted listing

### ISSUE THREAD

**Issue by benjaminaaron** [waltsims/Thesis_Template_CSE#32]
Any idea why I am getting these random red rectangles in the PDF? I first thought it might be the SyncTeX going a bit crazy, but they are still there when I turn that off :man_shrugging: 

With `HTML` it's especially wild, but I also have a red-rectangle incident in a `SPARQL` listing.

![image](https://user-images.githubusercontent.com/5141792/54320617-dbe08180-45ed-11e9-8266-c24fa5e94b8b.png)

I am compiling in Atom on Ubuntu if that might make a difference?

**Comment by waltsims** [comment]
It sounds like [hyperlinking](https://tex.stackexchange.com/questions/823/remove-ugly-borders-around-clickable-cross-references-and-hyperlinks) is the issue or your pdf viewer. I've seen those boxes for to symbolize links.

**Comment by benjaminaaron** [comment]
Thanks for the suggestion! I had no luck so far though, the red rectangles are still there. Will keep trying...

**Comment by benjaminaaron** [comment]
Ok, I found something hacky that works for me [here](https://tex.stackexchange.com/a/343506). 
I added these  lines in `settings.tex` below `\setminted`:
```latex
\usepackage{etoolbox}
\makeatletter
\AtBeginEnvironment{minted}{\dontdofcolorbox}
\def\dontdofcolorbox{\renewcommand\fcolorbox[4][]{##4}}
\makeatother
```
